version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "1.x"
    ignore:
      - dependency-name: "drupal/core-composer-scaffold"
        update-types: ["version-update:semver-major"]
      - dependency-name: "drupal/core-recommended"
        update-types: ["version-update:semver-major"]
