name: Sync GitHub issues to Jira
on:
  issues:
    types:
      - opened
      - closed
permissions:
  issues: write
  pull-requests: read
jobs:
  jira:
    uses: acquia/.github/.github/workflows/jira.yml@main
    secrets:
      jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
      jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
    with:
      project_key: 'ACMS'
